[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "transcript-parser"
version = "0.1.0"
description = "Transcript_Parser: a packaged Python project with CI, dev tooling, and Docker"
readme = "README.md"
authors = [{ name = "Mark R. Sepanski" }]
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = [
  "black>=24.3.0",
  "isort>=5.13.0",
  "autoflake>=2.3.1",
  "mypy>=1.10.0",
  "pytest>=8.2.0",
  "pytest-cov>=5.0.0"
]

[project.scripts]
transcript-parser = "transcript_parser.cli:main"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
