name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project with dev dependencies
        run: pip install -e ".[dev]"

      - name: Lint (black)
        run: black --check .

      - name: Lint (isort)
        run: isort --check-only .

      - name: Lint (autoflake)
        run: autoflake -r . --check

      - name: Type check (mypy)
        run: mypy .

      - name: Tests (pytest)
        run: pytest -q
