name: CI

on:
  push:
    branches: [ main, "feature/**", "fix/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Pre-commit (lint & type checks)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Tests
        run: |
          pytest -q -vv
