name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    name: CI / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils ghostscript
      - name: Install package (dev) + pin Black
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
          pip install black==24.8.0
      - name: Black (root config)
        run: black --config pyproject.toml --check .
      - name: Ruff
        run: ruff check .
      - name: isort
        run: isort --check-only .
      - name: Autoflake
        run: autoflake --check --recursive src tests

  typecheck:
    name: CI / typecheck
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils ghostscript
      - name: Install package (dev)
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: MyPy
        run: mypy src

  tests:
    name: CI / tests (3.11)
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils ghostscript
      - name: Install package (dev)
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Pytest
        run: pytest -q
