name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package with dev + Paddle deps
        run: |
          python -m pip install -U pip
          pip install -e ".[dev,paddle]"
      - name: Lint & type-check
        run: |
          black --check .
          isort --check-only .
          autoflake --check --recursive src tests
          mypy src
      - name: Test
        run: pytest -q
