name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: CI / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.5.* black==24.*
      - name: Check formatting (ruff format; black compatibility)
        run: |
          ruff format --check --line-length 120 .
          black --check --line-length 120 .
      - name: Lint (ruff check)
        run: |
          ruff check --select E,F,I,UP --ignore E203,E501 --line-length 120 .

  typecheck:
    name: CI / typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mypy + project
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy==1.* types-Pillow types-PyYAML types-setuptools
          python -m pip install -e ".[dev]"
      - name: mypy
        run: |
          mypy --ignore-missing-imports --pretty src

  tests:
    name: CI / tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: System deps (poppler for pdf2image)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"
      - name: Run tests
        run: |
          pytest -q
