
name: CI / Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system deps (poppler for pdf2image)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Install package (dev extras)
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Black
        run: black --check .

      - name: Ruff (lint + format check)
        run: ruff check .

      - name: isort
        run: isort --check-only .

      - name: Autoflake (check only)
        run: autoflake --check --recursive src tests

      - name: MyPy
        run: mypy src

      - name: Pytest
        run: pytest -q
